### ISSUE TITLE
OneWire outside sensor issue

### ISSUE THREAD

**Issue by japlab** [motoz/PellMon#89] opened 2018-01-06 23:40 UTC
Can you please advise me what to do.
I have two issues, the first is:
Six 18B20 onewire sensors is hooked up and running. 
For the first time on this setup- today the outside temperature dropped below zero and the sensor reading gave up and return error.

log:
> 2018-01-06 16:37:13,081 - INFO - stop
> 2018-01-06 16:37:13,082 - INFO - deactivated ScotteCom
> 2018-01-06 16:37:13,083 - INFO - deactivated CustomAlarms
> 2018-01-06 16:37:13,084 - INFO - deactivated SiloLevel
> 2018-01-06 16:37:13,085 - INFO - deactivated Consumption
> 2018-01-06 16:37:13,087 - INFO - deactivated Cleaning
> 2018-01-06 16:37:13,088 - INFO - deactivated Onewire
> 2018-01-06 16:37:13,168 - INFO - exiting
> 2018-01-06 16:37:14,009 - INFO - invalid setting for plugin_dirs
> 2018-01-06 16:37:14,021 - INFO - starting PellMon
> 2018-01-06 16:37:14,023 - INFO - Looking for plugins in /usr/lib/python2.7/dist-packages/Pellmonsrv/plugins
> 2018-01-06 16:37:14,236 - INFO - serial port ok
> 2018-01-06 16:37:14,310 - INFO - chip version detected as: 4.99F
> 2018-01-06 16:37:14,339 - INFO - Activated plugins: ScotteCom, CustomAlarms, SiloLevel, Consumption, Cleaning, Onewire
> 2018-01-06 16:37:14,395 - INFO - copied /var/lib/pellmon/nvrrd.db to /mnt/ramdisk/rrd.db
> 2018-01-06 16:37:19,343 - INFO - 'alarm2' state went from 'OK' to 'silo level below 20Kg'
> 2018-01-06 16:43:20,003 - INFO - 'alarm2' state went from 'silo level below 20Kg' to 'OK'
> 2018-01-06 22:43:16,444 - INFO - invalid value for outside_temp: error
> 2018-01-06 22:48:16,444 - INFO - invalid value for outside_temp: error
> 2018-01-06 22:57:16,444 - INFO - invalid value for outside_temp: error
> 2018-01-06 22:57:46,444 - INFO - invalid value for outside_temp: error

When polling the sensors in terminal:
> pi@raspberrypi:/sys/bus/w1/devices/w1_bus_master1/28-0317229237ff $ cat w1_slave
> fb ff 4b 46 7f ff 0c 10 06 : crc=06 YES
> fb ff 4b 46 7f ff 0c 10 06 t=-312
> pi@raspberrypi:/sys/bus/w1/devices/w1_bus_master1/28-0317229237ff $ 

Second question:
The web frontend will not show Event.

webinterface.conf:
> [frontpage_widgets]
> 
> row_1 = systemimage,events
> row_2 = graph
> row_3 = consumption24h,silolevel

pellmon.conf:
> [conf]
> config_dir = /etc/pellmon/conf.d
> 
> logfile = /var/log/pellmonsrv/pellmon.log
> 
>lloglevel = info

BR  Jan

**Comment by motoz** [comment] 2018-01-07 09:10
Hello Jan.
The issue with the onewire plugin and negative temperatures should already be fixed by this commit 234103910add61f899bf43fb7dac6caa3f89ca4e which is included in the newest pre-release  0.7.1-alpha1. Let me know if you are already running that and still see the error. 

The missing events might be caused by your adblocker, ublock origin is know to mistakenly believe that the javascript code that updates the event view is somehow suspicious so it's blocked. If  you are using ublock origin the simplest fix is to just disable it for pellmon.

**Comment by japlab** [comment] 2018-01-07 18:18
Hi Anders
I was running 0.7.0 - when updating to 0.7.1-alpha the problem is hereby solved.
In Denmark the outside tempereaure is current +2degC. 
I cooled the sensor down to minus 26 deg.C with freezing spray. ;-) All working now.
Regarding that the "Event" was not showing up on the web frontend- As you suggested, It was the uBlock.
Thank you for the kind and fast support. I appriciate you dedication and skills. 
May I wish you a happy new year. 
Best regards 
Jan Peitersen, oz1ftx
new pictures [here](https://www.icloud.com/sharedalbum/da-dk/#B0QGI9HKKGCgXJm)

**Closed as completed** 2018-03-21 08:10 UTC
