### ISSUE TITLE
Can´t access woody

### ISSUE THREAD

**Issue by trikker77** [motoz/PellMon#69] opened 2015-12-18 13:53 UTC
Hi
I´m can´t access my woody from Raspberry Pi 2. I made the test with Windmill and it seems to have some kind of communication. 
[Ny side.pdf](https://github.com/motoz/PellMon/files/66649/Ny.side.pdf)
Can i do some more test from Windmill?
Recards
Trikker

**Comment by motoz** [comment] 2015-12-18 14:12
Looking at the screenshot you attached I suppose 'jhfhgjh' is what you transmitted to your woody and  the right column 'reply' containing 'E1' + 13 + 10 then is a correct answer to the erroneous request, meaning 'checksum error + newline + linefeed'.

You could try transmitting 'Z000000Z', that should be a valid request with correct checksum, but the 'E1' answer already means that communication is working if that is what you are looking for.

Are you trying to run PellMon on the raspberry or some other software?

**Comment by motoz** [comment] 2015-12-18 14:28
Or when I remember to think before I write, the answer you got did not contain a checksum, which means that you have a rather old woody version. Old versions did not have checksums on messages, so a correct request would be Z000000 + newline + linefeed (13 and 10). PellMon did not work with those older burners until quite recently (v0.3.0), which burner version do you have?

**Comment by trikker77** [comment] 2015-12-18 14:37
It woorks
[Ny side2.pdf](https://github.com/motoz/PellMon/files/66700/Ny.side2.pdf)
But what are the problem at the Raspberry Pi?

**Comment by motoz** [comment] 2015-12-18 14:41
You need to give me some more information, what is your burner software version, something like, 4.12, 5.04. It should be printed on the memory chip inside your controller.

How do  you connect your raspberry to the controller?

And what are you trying to do on the raspberry? Are you trying to run PellMon?

**Comment by trikker77** [comment] 2015-12-18 14:49
Version 6.60
I´m connecting my Raspberry with a USB to Seriel converter.
Running Pellmon.

**Comment by trikker77** [comment] 2015-12-18 15:02
And Pellmon 0.5.0

**Comment by motoz** [comment] 2015-12-18 15:33
Ok, then it should work alright.

I suppose you have pellmon up and running, what is in the pellmon log?

**Comment by trikker77** [comment] 2015-12-18 15:46
2015-12-18 16:45:55,787 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,783 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,779 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,776 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,772 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,768 - INFO - Timeout again, give up and return fail
2015-12-18 16:45:55,764 - INFO - Timeout again, give up and return fail

**Comment by trikker77** [comment] 2015-12-18 15:55
2015-12-18 16:55:31,543 - INFO - Timeout again, give up and return fail
2015-12-18 16:55:31,052 - INFO - error in retry [Errno 0] GetItem failed
2015-12-18 16:55:29,538 - INFO - Timeout again, give up and return fail
2015-12-18 16:55:27,533 - INFO - Timeout again, give up and return fail
2015-12-18 16:55:26,048 - INFO - IOError: GetItem failed, Trying Z01...
2015-12-18 16:55:25,526 - INFO - Timeout again, give up and return fail
2015-12-18 16:55:23,519 - INFO - Timeout again, give up and return fail

**Comment by motoz** [comment] 2015-12-18 16:07
Can you also give me the contents of the log right after restarting pellmon?

**Comment by trikker77** [comment] 2015-12-18 16:32
The last comment is right after restart.

**Comment by motoz** [comment] 2015-12-18 16:49
Really? Seems unlikely. Should look something like:
2015-12-08 22:11:49,121 - INFO - Activated plugins: ScotteCom, CustomAlarms, Calculate, OWFS, SiloLevel, Consumption, Cleaning
2015-12-08 22:11:48,722 - INFO - chip version detected as: 6.33
2015-12-08 22:11:48,562 - INFO - serial port ok
2015-12-08 22:11:46,209 - INFO - starting pelletMonitor 

At least the 'starting pelletMonitor' should be there, then it's interesting to know what happens just after that.

To get some more information in the log you can change the log setting in /etc/pellmon/pellmon.conf from
loglevel = info
to
loglevel = debug
and restart
There is quite a lot of noise in the log then, but the beginning after restart could be interesting. The log file is in /usr/local/var/log/pellmonsrv/pellmon.log , so you can look there also since the webinterface shows only the latest 150 rows.

**Comment by trikker77** [comment] 2015-12-18 17:28
2015-12-06 09:20:53,371 - INFO - starting pelletMonitor
2015-12-06 09:20:53,805 - INFO - serial port ok
2015-12-06 09:20:55,833 - INFO - Timeout again, give up and return fail
2015-12-06 09:20:55,851 - INFO - protocol checksums turned off
2015-12-06 09:20:57,856 - INFO - Timeout again, give up and return fail
2015-12-06 09:20:59,878 - INFO - Timeout again, give up and return fail
2015-12-06 09:20:59,894 - INFO - can't read program version, assuming 4.00
2015-12-06 09:21:01,898 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:01,915 - INFO - Not connected? Check the cables
2015-12-06 09:21:01,929 - INFO - Activated plugins: ScotteCom, Cleaning, SiloLevel, Consumption
2015-12-06 09:21:03,940 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:04,224 - INFO - Created rrd database: rrdtool create /usr/local/var/lib/pellmon/rrd.db --step 30 DS:data1:GAUGE:120:U:U DS:data2:GAUGE:120:U:U DS:data3:GAUGE:120:U:U DS:dat$
2015-12-06 09:21:06,329 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:08,334 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:10,340 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:10,361 - INFO - IOError: GetItem failed,  Trying Z01...
2015-12-06 09:21:12,347 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:14,354 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:15,366 - INFO - error in retry [Errno 0] GetItem failed
2015-12-06 09:21:16,361 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:18,368 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:20,371 - INFO - IOError: GetItem failed,  Trying Z01...
2015-12-06 09:21:20,375 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:22,381 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:24,388 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:25,379 - INFO - error in retry [Errno 0] GetItem failed
2015-12-06 09:21:26,394 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:28,401 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:30,382 - INFO - IOError: GetItem failed,  Trying Z01...
2015-12-06 09:21:30,408 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:32,413 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:34,420 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:35,386 - INFO - error in retry [Errno 0] GetItem failed
2015-12-06 09:21:36,426 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:38,431 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:40,391 - INFO - IOError: GetItem failed,  Trying Z01...
2015-12-06 09:21:40,438 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:42,443 - INFO - Timeout again, give up and return fail
2015-12-06 09:21:44,449 - INFO - Timeout again, give up and return fail

**Comment by trikker77** [comment] 2015-12-18 17:39
2015-12-18 18:39:20,010 - DEBUG - serial written
2015-12-18 18:39:20,007 - DEBUG - serial write
2015-12-18 18:39:20,004 - DEBUG - sendFrame = Z000000
2015-12-18 18:39:20,001 - DEBUG - got command
2015-12-18 18:39:19,998 - INFO - Timeout again, give up and return fail
2015-12-18 18:39:19,994 - DEBUG - Try to put False, answer was empty
2015-12-18 18:39:19,991 - DEBUG - answer:

**Comment by motoz** [comment] 2015-12-18 17:55
Ok that confirms it, it can't read anything at all.

I suppose you use the same usb-serial adapter as you succesfully tried with windmill on windows? That's really strange then, I don't really know why it doesn't work.

You could try shutting of pellmon

    sudo service pellmonsrv stop

and then run the attached test program:

    wget https://github.com/motoz/PellMon/files/66959/v4test.py.zip
    unzip v4test.py.zip
    python v4test.py

copy paste the output here if it prints something
[v4test.py.zip](https://github.com/motoz/PellMon/files/66959/v4test.py.zip)

**Comment by trikker77** [comment] 2015-12-18 17:59
pi@raspberrypi /usr/local/var/log/pellmonsrv $ sudo python v4test.py
read Z000000
response:

read Z010000
response:

read Z020000
response:

read Z030000
response:h▒▒'i-,
(▒
ww$
"Uq
Y(g
]▒@
aA&
-
;SLILi1#Bl▒'i f5A'z
104 130 130 104 8 27 114 39 105 22 4 45 44 1 4 7 0 0 0 12 6 40 146 8 0 12 20 119 119 36 0 12 34 85 113 4 0 12 89 40 103 0 0 12 93 135 64 0 0 12 97 65 38 0 0 12 45 22 0 0 0 12 59 83 0 0 0 76 6 73 57 8 0 76 20 105 49 35 0 66 108 255 21 15 39 105 22 4 0 0 32 2 0 0 0 0 1 0 102 0 0 0 0 0 0 0 53 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 25 65 4 0 0 0 39 1 24 18 21 0 122 22
read Z040000
response:

pi@raspberrypi /usr/local/var/log/pellmonsrv $

**Comment by trikker77** [comment] 2015-12-18 18:05
Yes, i´m use the same usb adapter

**Comment by motoz** [comment] 2015-12-18 18:14
So it's not not completely dead then, request  Z03 got some kind of answer even if corrupted. I wonder if possibly a bad power supply on the raspberry could cause that. The serial adapter is powered from the usb port and the raspberry is a bit famous for having weak power transfer to the usb ports so a weak 5V supply could possibly be the cause. Do you have another micro usb power adapter to try with? Or a powered usb hub to connect the usb adapter?

**Comment by trikker77** [comment] 2015-12-18 18:41
I just change the power supply (2Amps), but now i don´t have enythings on the test.

read Z000000
response:

read Z010000
response:

read Z020000
response:

read Z030000
response:

read Z040000
response:

**Comment by motoz** [comment] 2015-12-18 18:56
I don't suppose you have another raspberry pi lying around? It does really start to look like a hardware failure.

The test prog works on windows also if you edit it to change '/dev/ttyUSB0' to 'COM3' or 'COM4' or whatever the serial port shows up as (and you need to install python 2.7 from https://www.python.org/downloads/windows) if you want to make sure it isn't the serial adapter.

**Comment by trikker77** [comment] 2015-12-18 19:01
I have 4 pcs.
what about on a linux pc?

**Comment by motoz** [comment] 2015-12-18 19:10
Well of course even better, I just assumed you ran windows when I found some screenshots of a windows sw called windmill when I googled that.

**Comment by motoz** [comment] 2016-01-11 06:53
Any news on this?

**Comment by trikker77** [comment] 2016-01-11 08:14
No, tried to change the communication chip, but still no result.

**Comment by motoz** [comment] 2016-01-11 08:22
Did you try running the test prog on a pc?

**Comment by trikker77** [comment] 2016-01-11 08:24
Yes, with python 4test from Linux.

**Comment by motoz** [comment] 2016-01-11 08:28
Did you get any response on the pc?

**Comment by trikker77** [comment] 2016-01-11 08:29
No

**Comment by motoz** [comment] 2016-01-11 08:32
Ok, then I suppose there must be something wrong with your controller. Not much to do, changing the processor chip could fix it (or not).

**Comment by trikker77** [comment] 2016-01-11 08:37
I have sent a mail to stokersoft about the problem, but still no answer.

**Comment by peterfarsinsen** [comment] 2016-01-11 08:59
Did you try another serial -> usb converter or do you have the option to try another computer that has a real serial port?

**Comment by trikker77** [comment] 2016-01-11 09:02
2 different converter, but I will find a PC with Serial.

**Comment by motoz** [comment] 2016-01-11 09:16
This is really strange, in the test you did with the windmill sw you seem to get a correct answer to the 'Z000000Z' frame, but you only posted the first few characters of the response so I can't say if its all ok. The response from the test prog on the Z03 frame however is completely garbled from the beginning. I wonder if it is possible that you found a usb-serial coverter with non-working linux driver. It's usually the other way around, an cheap adapter that gives you endless problems because of a bad windows driver just works on linux, but I suppose it is possible. Did you run windmill on windows or linux?

**Comment by trikker77** [comment] 2016-01-11 09:31
Maybe the old test have been found my m-bus converter, at this time its was plugged in.

**Comment by motoz** [comment] 2016-01-11 09:36
Do you mean that you have several usb-serial adapters? If that is the case you have to make sure you are talking to the correct one. ttyUSB0 or ttyUSB1 or 2 or 3...

**Comment by trikker77** [comment] 2016-01-11 09:51
Yes I now, my mistakes in the first place. Now i only connect the Serial adapter.

**Comment by motoz** [comment] 2016-01-12 19:25
Does that mean pellmon is working now? If that's the case I can close the issue. If not I would like to know what the output is when you run the test program against the correct tty device.

**Comment by trikker77** [comment] 2016-01-13 09:46
Still not working and I will write again with the test result.

**Comment by motoz** [comment] 2016-01-25 06:40
Closed due to no activity

**Closed by motoz** 2016-01-25 06:40 UTC
Labels: question

**Comment by osos** [comment] 2017-04-02 19:29
@trikker77, any newz on this one.

**Comment by trikker77** [comment] 2017-04-02 21:39
No, I dont spend more time on this, because I dont get any contact after change the communications chip. :-(
